=== SqrtMinusOne/ERMaket/xml/er.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="ermaket" xmlns="ermaket" xmlns:ns="ermaket" elementFormDefault="qualified">

    <!-- Простые типы полей в БД -->
    <xs:simpleType name="staticTypes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="boolean" />
            <xs:enumeration value="float8" />
            <xs:enumeration value="float4" />
            <xs:enumeration value="date" />
            <xs:enumeration value="json" />
            <xs:enumeration value="int8" />
            <xs:enumeration value="int4" />
            <xs:enumeration value="int2" />
            <xs:enumeration value="time" />
            <xs:enumeration value="timestamp" />
            <xs:enumeration value="text" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Типы полей с изменяемым размером -->
    <xs:simpleType name="fieldTypes">
        <xs:union memberTypes="staticTypes">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="varchar\([0-9]{1,7}\)" />
                    <xs:pattern value="decimal\([0-9]{1,10}(,( )*[0-9]{1,10})?\)" />
                    <xs:pattern value="enum\(( |\'[ \S]*\'(,)?)+\)" />
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>

    <!-- Атрибут сущности -->
    <xs:complexType name="attributeType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="isPk" type="xs:boolean" default="false" minOccurs="0" />
            <xs:element name="isNull" type="xs:boolean" default="false" minOccurs="0" />
            <xs:element name="type" type="fieldTypes" />
        </xs:sequence>
    </xs:complexType>

    <!-- Сущность -->
    <xs:complexType name="entityType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="systemTable" type="xs:string" minOccurs="0" />
            <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required" />
    </xs:complexType>

    <!-- Сторона связи -->
    <xs:complexType name="relationSideType">
        <xs:all>
            <xs:element name="idRef" type="xs:integer" />
            <xs:element name="isMandatory" type="xs:boolean" />
            <xs:element name="isMultiple" type="xs:boolean" />
        </xs:all>
    </xs:complexType>

    <!-- Связь -->
    <xs:complexType name="relationType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="side" type="relationSideType" minOccurs="2" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <!-- Корень -->
    <xs:element name="erModel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entity" type="entityType" maxOccurs="unbounded" />
                <xs:element name="relation" type="relationType" minOccurs="0" maxOccurs="unbounded" />
                <!-- Id сущностей в связи могут повторяться; связь может быть рекурсивной -->
            </xs:sequence>
        </xs:complexType>
        <xs:key name="entity-key">
            <xs:selector xpath="ns:entity" />
            <xs:field xpath="@id" />
        </xs:key>
        <xs:keyref name="entity-keyref" refer="entity-key">
            <xs:selector xpath="ns:relation/ns:side/ns:idRef" />
            <xs:field xpath="." />
        </xs:keyref>
        <xs:unique name="enitity-unique-name">
            <xs:selector xpath="ns:entity/ns:name" />
            <xs:field xpath="." />
        </xs:unique>
    </xs:element>

</xs:schema>

=== SqrtMinusOne/ERMaket/xml/example.xml
<?xml version="1.0" ?>
<erModel xmlns="ermaket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ermaket er.xsd">
    <entity id="0">
        <name>User</name>
        <attribute>
            <name>Name</name>
            <isPk>true</isPk>
            <type>varchar[256]</type>
        </attribute>
    </entity>
    <entity id="1">
        <name>Task</name>
        <attribute>
            <name>Name</name>
            <type>varchar[256]</type>
        </attribute>
        <attribute>
            <name>Due date</name>
            <type>timestamp</type>
        </attribute>
        <attribute>
            <name>Description</name>
            <type>text</type>
        </attribute>
    </entity>
    <entity id="2">
        <name>Subtask</name>
        <attribute>
            <name>Name</name>
            <isPk>true</isPk>
            <type>varchar[256]</type>
        </attribute>
    </entity>
    <entity id="3">
        <name>Comment</name>
        <attribute>
            <name>Text</name>
            <type>text</type>
        </attribute>
    </entity>
    <entity id="4">
        <name>List</name>
        <attribute>
            <name>Name</name>
            <type>varchar[256]</type>
        </attribute>
    </entity>
    <entity id="5">
        <name>Attachment</name>
        <attribute>
            <name>Contents</name>
            <type>text</type>
        </attribute>
    </entity>
    <entity id="6">
        <name>Item</name>
        <attribute>
            <name>Name</name>
            <type>varchar[256]</type>
        </attribute>
        <attribute>
            <name>Status</name>
            <type>enum('Complete', 'Not complete')</type>
        </attribute>
    </entity>
    <relation>
        <name>is_author_to</name>
        <side>
            <idRef>0</idRef>
            <isMandatory>true</isMandatory>
            <isMultiple>false</isMultiple>
        </side>
        <side>
            <idRef>3</idRef>
            <isMandatory>false</isMandatory>
            <isMultiple>true</isMultiple>
        </side>
    </relation>
    <relation>
        <name>is_assigned_to</name>
        <side>
            <idRef>0</idRef>
            <isMandatory>false</isMandatory>
            <isMultiple>true</isMultiple>
        </side>
        <side>
            <idRef>1</idRef>
            <isMandatory>false</isMandatory>
            <isMultiple>true</isMultiple>
        </side>
    </relation>
    <relation>
        <name>is_written_to</name>
        <side>
            <idRef>3</idRef>
            <isMandatory>false</isMandatory>
            <isMultiple>true</isMultiple>
        </side>
        <side>
            <idRef>1</idRef>
            <isMandatory>true</isMandatory>
            <isMultiple>false</isMultiple>
        </side>
    </relation>
    <relation>
        <name>belongs_to</name>
        <side>
            <idRef>1</idRef>
            <isMandatory>false</isMandatory>
            <isMultiple>true</isMultiple>
        </side>
        <side>
            <idRef>4</idRef>
            <isMandatory>true</isMandatory>
            <isMultiple>false</isMultiple>
        </side>
    </relation>
    <relation>
        <name>is_attached</name>
        <side>
            <idRef>5</idRef>
            <isMandatory>false</isMandatory>
            <isMultiple>true</isMultiple>
        </side>
        <side>
            <idRef>1</idRef>
            <isMandatory>true</isMandatory>
            <isMultiple>false</isMultiple>
        </side>
    </relation>
    <relation>
        <name>contains</name>
        <side>
            <idRef>1</idRef>
            <isMandatory>true</isMandatory>
            <isMultiple>false</isMultiple>
        </side>
        <side>
            <idRef>2</idRef>
            <isMandatory>false</isMandatory>
            <isMultiple>true</isMultiple>
        </side>
    </relation>
    <relation>
        <name>contains</name>
        <side>
            <idRef>2</idRef>
            <isMandatory>true</isMandatory>
            <isMultiple>false</isMultiple>
        </side>
        <side>
            <idRef>6</idRef>
            <isMandatory>false</isMandatory>
            <isMultiple>true</isMultiple>
        </side>
    </relation>
</erModel>

=== SqrtMinusOne/ERMaket/xml/examples/small_for_article.xml
<?xml version="1.0" ?>
<erModel xmlns="ermaket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ermaket er.xsd">
    <entity id="1">
        <name>Task</name>
        <attribute>
            <name>Name</name>
            <isPk>true</isPk>
            <type>varchar(200)</type>
        </attribute>
        <attribute>
            <name>Due date</name>
            <type>date</type>
        </attribute>
        <attribute>
            <name>Description</name>
            <type>text</type>
        </attribute>
    </entity>
    <entity id="2">
        <name>List</name>
        <attribute>
            <name>Name</name>
            <isPk>true</isPk>
            <type>varchar(200)</type>
        </attribute>
    </entity>
    <relation>
        <name>belongs_to</name>
        <side>
            <idRef>1</idRef>
            <isMandatory>false</isMandatory>
            <isMultiple>true</isMultiple>
        </side>
        <side>
            <idRef>2</idRef>
            <isMandatory>true</isMandatory>
            <isMultiple>false</isMultiple>
        </side>
    </relation>
</erModel>
